# Test Configuration Registry
androidphone-dw:
    mode: remote
    os: android
    browser: app
    server : https://0.0.0.0:4723/wd/hub
    deviceName: "SamsungTabA"
    deviceId: "3100fde5c12d8400"    
    platformName: "Android"
    launchTimeout: "100000"